# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MaevesGarage',
                'doc_host': 'https://Andersen98.github.io',
                'git_url': 'https://github.com/Andersen98/MaevesGarage',
                'lib_path': 'MaevesGarage'},
  'syms': {'MaevesGarage.core': {'MaevesGarage.core.foo': ('core.html#foo', 'MaevesGarage/core.py')}}}
